In [2]:
# imports
import numpy as np 
import sklearn as sklearn
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

print("numpy version {}".format(np.__version__))
print("sklearn version {}".format(sklearn.__version__))


numpy version 1.18.1
sklearn version 0.22.2.post1


In [3]:
# define example
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values = array(data)
print(values)


['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']


In [7]:
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print("encoded of shape {} is now {}".format(integer_encoded.shape, integer_encoded))



encoded of shape (10,) is now [0 0 2 0 1 1 2 0 2 1]


In [8]:
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
print("encoded of shape {} is now {}".format(integer_encoded.shape, integer_encoded))


onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)


encoded of shape (10, 1) is now [[0]
 [0]
 [2]
 [0]
 [1]
 [1]
 [2]
 [0]
 [2]
 [1]]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [6]:
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)


['cold']
