In [1]:
import tensorflow as tf
session = tf.Session()

In [2]:
testGraph = tf.Graph()
with testGraph.as_default():
    testVariable = tf.Variable(30, name='dude')
    initialize = tf.global_variables_initializer()
  
with tf.Session(graph = testGraph) as testSession:
    testSession.run(initialize)
    print(testSession.run(testVariable))
    
    

30


constants for TF; hese do not need to get initialized beforee running the graph

In [3]:
testConstant = tf.constant(12, dtype = 'float32')
with tf.Session() as constantsSession:
    print(constantsSession.run(testConstant))
    
    

12.0


Variables in TF; these need to have the model initialize them before running

In [5]:
testVar02 = tf.Variable(testConstant * 12)
model = tf.global_variables_initializer()
with tf.Session() as varSession02:
    varSession02.run(model)
    print(varSession02.run(testVar02))
    

144.0


In [4]:
place03 = tf.placeholder("float", [None, 4])
calc03 = place03 * 2 + 3

data03a = [[12, 2, 0, -2], [14, 4, 9, 2]]
data03b = [[24, 4, 0, -8], [28, 8, 19, -4]]

# run model with first data
with tf.Session() as placeSession:
    placeRun03a = placeSession.run(calc03, feed_dict={place03: data03a})
    print(placeRun03a)
    
    placeRun03b = placeSession.run(calc03, feed_dict={place03: data03b})
    print(placeRun03b)
    
    


[[27.  7.  3. -1.]
 [31. 11. 21.  7.]]
[[ 51.  11.   3. -13.]
 [ 59.  19.  41.  -5.]]


In [5]:
place03 = tf.placeholder("float", [None, 4])
calc03 = place03 * 2 + 3

data03a = [[12, 2, 0, -2], [14, 4, 9, 2]]
data03b = [[24, 4, 0, -4], [28, 8, 19, -8]]

# run model with first data
with tf.Session() as placeSession:
    placeRun03a = placeSession.run(calc03, feed_dict={place03: data03a})
    print(placeRun03a)
    
    placeRun03b = placeSession.run(calc03, feed_dict={place03: data03b})
    print(placeRun03b)
    
    


[[27.  7.  3. -1.]
 [31. 11. 21.  7.]]
[[ 51.  11.   3.  -5.]
 [ 59.  19.  41. -13.]]


Fixed tensors

In [7]:
zeroTensor = tf.zeros([3,5])
with tf.Session() as zeroSession:
    print(zeroSession.run(zeroTensor))
    

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
oneTensor = tf.ones([3,5])
with tf.Session() as fixedSession:
    print(fixedSession.run(oneTensor))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
fillTensor = tf.fill([3,5], 17)
with tf.Session() as fixedSession:
    print(fixedSession.run(fillTensor))

[[17 17 17 17 17]
 [17 17 17 17 17]
 [17 17 17 17 17]]


In [10]:
diagTensor = tf.diag([1, 2, 3, 4, 5])
with tf.Session() as fixedSession:
    print(fixedSession.run(diagTensor))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [11]:
# range tensor with start, stop (not included) and step
rangeTensor = tf.range(start = 2, limit = 20, delta = 2)
with tf.Session() as fixedSession:
    print(fixedSession.run(rangeTensor))

[ 2  4  6  8 10 12 14 16 18]


In [14]:
# linear spaced tensor, start, stop (both must be float_) and number of elemnnts
linTensor = tf.linspace(10.0, 37.0, 9)
with tf.Session() as fixedSession:
    print(fixedSession.run(linTensor))

[10.    13.375 16.75  20.125 23.5   26.875 30.25  33.625 37.   ]


In [15]:
# uniform distribution
uniformTensor = tf.random_uniform([4, 5], minval = 0, maxval = 2)
with tf.Session() as fixedSession:
    print(fixedSession.run(uniformTensor))

[[0.51746035 0.06943727 0.00645161 1.4721625  0.64677954]
 [0.27314973 0.22177267 1.8479772  0.7799077  1.6363573 ]
 [1.136267   0.28787994 1.6554317  1.4114292  0.53072286]
 [0.10410643 1.1086657  1.5920417  0.02343369 1.6746941 ]]


In [16]:
 # normal distribution
 normalTensor = tf.random_normal([4, 5], mean = 1, stddev = 0.2)
 with tf.Session() as fixedSession:
    print(fixedSession.run(normalTensor))

[[0.9614617  1.1474714  1.2464426  0.8340354  0.79446864]
 [1.1632086  0.85722303 0.84283525 1.0568315  0.86787736]
 [1.0305777  1.1227076  1.0992657  1.0925635  0.914611  ]
 [1.2162497  1.0071027  0.66978145 0.6722386  0.9820409 ]]


Shuffling methods


In [18]:
# create a diag tenso and shuffle it
diagTensor02 = tf.diag([1, 2, 3, 4])
with tf.Session() as fixedSession:
    print(fixedSession.run(diagTensor02))
    
shuffleTensor = tf.random_shuffle(diagTensor02)
with tf.Session() as fixedSession:
    print(fixedSession.run(shuffleTensor))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[0 0 3 0]
 [1 0 0 0]
 [0 2 0 0]
 [0 0 0 4]]


In [22]:
# create a diag tenso and crop
cropTensor = tf.random_crop(diagTensor02, [2, 2])
with tf.Session() as fixedSession:
    print(fixedSession.run(diagTensor02))
    print(fixedSession.run(cropTensor))
    

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[0 0]
 [2 0]]
