In [1]:
# import numpy
import numpy as np



In [2]:
a = np.array(['dude', 'yo'])
print("a is of type: {}".format(type(a)))
print("a value is: {}".format(a))




a is of type: <type 'numpy.ndarray'>
a value is: ['dude' 'yo']


In [3]:
# add o array
a = np.append(a, "dog")

print("a is of type: {}".format(type(a)))
print("a value is: {}".format(a))

for i in a:
    print("value of element is: {} of type: {}".format(i, type(i)))


a is of type: <type 'numpy.ndarray'>
a value is: ['dude' 'yo' 'dog']
value of element is: dude of type: <type 'numpy.string_'>
value of element is: yo of type: <type 'numpy.string_'>
value of element is: dog of type: <type 'numpy.string_'>


In [5]:
for i, ele in enumerate(a):
    print("for index {} of type {} get value {} of ype {}".format(i, type(i), ele, type(ele)))
    
    
    

for index 0 of type <class 'int'> get value dude of ype <class 'numpy.str_'>
for index 1 of type <class 'int'> get value yo of ype <class 'numpy.str_'>
for index 2 of type <class 'int'> get value dog of ype <class 'numpy.str_'>
for index 3 of type <class 'int'> get value dog of ype <class 'numpy.str_'>


In [7]:
# try loat array
flo = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 4.1, 2.1, 0.1])

for i, ele in enumerate(flo):
    print("for index {} of type {} get value {} of ype {}".format(i, type(i), ele, type(ele)))


for index 0 of type <class 'int'> get value 1.0 of ype <class 'numpy.float64'>
for index 1 of type <class 'int'> get value 2.0 of ype <class 'numpy.float64'>
for index 2 of type <class 'int'> get value 3.0 of ype <class 'numpy.float64'>
for index 3 of type <class 'int'> get value 4.0 of ype <class 'numpy.float64'>
for index 4 of type <class 'int'> get value 5.0 of ype <class 'numpy.float64'>
for index 5 of type <class 'int'> get value 6.0 of ype <class 'numpy.float64'>
for index 6 of type <class 'int'> get value 4.1 of ype <class 'numpy.float64'>
for index 7 of type <class 'int'> get value 2.1 of ype <class 'numpy.float64'>
for index 8 of type <class 'int'> get value 0.1 of ype <class 'numpy.float64'>


In [8]:
# np functions
print("max of {} is {}".format(flo, np.max(flo)))
print("avg of {} is {}".format(flo, np.average(flo)))
print("index max index of {} is {}".format(flo, np.argmax(flo)))
print("median of {} is {}".format(flo, np.median(flo)))


max of [1.  2.  3.  4.  5.  6.  4.1 2.1 0.1] is 6.0
avg of [1.  2.  3.  4.  5.  6.  4.1 2.1 0.1] is 3.033333333333333
index max index of [1.  2.  3.  4.  5.  6.  4.1 2.1 0.1] is 5
median of [1.  2.  3.  4.  5.  6.  4.1 2.1 0.1] is 3.0


In [11]:
# create 4x3 random matrix
mat = np.random.rand(4, 3)

print("matrux of type {} is: {}".format(type(mat),mat))

for i in mat:
    print("i is: {}".format(i))
    
    


matrux of type <class 'numpy.ndarray'> is: [[0.65096758 0.81091133 0.27354534]
 [0.16668947 0.5491192  0.34852656]
 [0.77831379 0.55127764 0.17136794]
 [0.06392346 0.7242392  0.43803113]]
i is: [0.65096758 0.81091133 0.27354534]
i is: [0.16668947 0.5491192  0.34852656]
i is: [0.77831379 0.55127764 0.17136794]
i is: [0.06392346 0.7242392  0.43803113]


In [19]:
for i in mat:
    print("i of type {} and shape{} is: {}".format(type(i), i.shape, i))
    for j in i:
        print("j of type {} and shape{} is: {}".format(type(j), j.shape, j))
    
    

i of type <class 'numpy.ndarray'> and shape(3,) is: [0.65096758 0.81091133 0.27354534]
j of type <class 'numpy.float64'> and shape() is: 0.6509675838697435
j of type <class 'numpy.float64'> and shape() is: 0.8109113250363943
j of type <class 'numpy.float64'> and shape() is: 0.2735453429090585
i of type <class 'numpy.ndarray'> and shape(3,) is: [0.16668947 0.5491192  0.34852656]
j of type <class 'numpy.float64'> and shape() is: 0.1666894722966492
j of type <class 'numpy.float64'> and shape() is: 0.549119201283368
j of type <class 'numpy.float64'> and shape() is: 0.34852656149511485
i of type <class 'numpy.ndarray'> and shape(3,) is: [0.77831379 0.55127764 0.17136794]
j of type <class 'numpy.float64'> and shape() is: 0.7783137898787282
j of type <class 'numpy.float64'> and shape() is: 0.5512776411212129
j of type <class 'numpy.float64'> and shape() is: 0.17136793949862317
i of type <class 'numpy.ndarray'> and shape(3,) is: [0.06392346 0.7242392  0.43803113]
j of type <class 'numpy.float6

In [21]:
mat_a = np.random.rand(4,3)
mat_b = np.random.rand(3,2)

print("matrix a of type {} and shape {} is {}".format(type(mat_a), mat_a.shape, mat_a))
print("matrix b of type {} and shape {} is {}".format(type(mat_b), mat_b.shape, mat_b))



mat_c = np.matmul(mat_a, mat_b)
print("matrix c of type {} and shape {} is {}".format(type(mat_c), mat_c.shape, mat_c))



matrix a of type <class 'numpy.ndarray'> and shape (4, 3) is [[0.44297154 0.03406091 0.14928529]
 [0.86278716 0.50914926 0.78726542]
 [0.11198454 0.52323787 0.73473339]
 [0.5873176  0.09246436 0.31821341]]
matrix b of type <class 'numpy.ndarray'> and shape (3, 2) is [[0.35402488 0.39215508]
 [0.45765991 0.91053475]
 [0.10538376 0.14500409]]
matrix c of type <class 'numpy.ndarray'> and shape (4, 2) is [[0.1881435  0.22637415]
 [0.62143032 0.91610116]
 [0.35653927 0.62688091]
 [0.2837768  0.36065383]]


In [22]:
mat_d = mat_a * mat_b


ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 